---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhao.
--- DateTime: 2020/3/1 20:59
---                                                                   m


local Mock = require("LuaMock.Mock")

local function testFoo()
    local TestMock = Mock:new("TestMock")
    TestMock:mock("foo", "outputPara", 1)
    print(TestMock.foo())
    TestMock:verify()
end

return testFoo()                                 